name: Williamguntercreative
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: William Gunter Creative
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151319'
    - '#3c3b40'
    - '#595f68'
    - '#fef1d7'
    - '#93aec2'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
