layout_spectrum: 1
typography_spectrum: 1
color:
  saturation: 1
  lightness: 0.7401434
  brandStrength: 0.671473
  rhythmicContrast: 0.6648746
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Williamguntercreative
